baseURL = 'https://natyharary.github.io'
languageCode = 'en-us'
title = "Naty Harary's Personal Website"
theme = 'natyharary_theme'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true