baseURL = 'https://natyharary.github.io'
theme = "salinger"
title = "Naty Harary"
copyright = 'Naty Harary'
ignoreErrors = ["error-remote-getjson"]
languageCode = 'en-us'

[params]
DateFormat = "January 2006"

author = "Naty Harary"
description = "I'm a software engineer based in Tel Aviv, Israel. I also do wood-stuff and yoga!"
header = "<strong>Hi, I'm Naty. 👋 </strong>"
keywords = [ "Portfolio", "developer", "coding", "maker"]
showHeaderOnHomepage = false
#googleAnalytics = ""
twemoji = true
text404 = "You got nowhere. I'm sorry. Maybe it is your fault, maybe it is mine. Take the time to embrace the nothingness, the silence. Stay for a while. Or go back <a href=\"/\">home</a>. </br></br> <iframe src=\"https://giphy.com/embed/l3fQheV6fal3N5dgA\" width=\"480\" height=\"480\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen></iframe> "
#fontawesomekitcode = ""


[permalinks]
  '/' = '/:slug/'
  'projects' = '/:slug/'

[[params.social]]
name = "github"
url = "https://github.com/natyharary"
icon = "fa fa-github"
before = "Reach me on "

[[params.social]]
name = "email"
icon = "fa fa-envelope"
url = "mailto:naty.harary@gmail.com"
before = "or drop me a line on"



[Menu]
[[Menu.Main]]
name = "Projects."
url = "/projects/"
weight = 1

[[Menu.Main]]
name = "Contact me."
url = "mailto:naty.harary@gmail.com"
weight = 2

[taxonomies]
	tag = "tags"
	category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true